import React from "react";
import {
  useNavigate,
  Outlet,
  useLocation,
} from "react-router-dom";

const Reports = () => {

  const navigate = useNavigate();
  const location = useLocation();

  const reportCards = [

    {
      title: "Inventory Report",
      value: "245",
      subtitle: "Products",
      color: "blue",
      path: "/reports/inventory",
    },

    {
      title: "Purchase Report",
      value: "42",
      subtitle: "POs Completed",
      color: "green",
      path: "/reports/purchase",
    },

    {
      title: "Supplier Report",
      value: "48",
      subtitle: "Suppliers",
      color: "orange",
      path: "/reports/suppliers",
    },

    {
      title: "Stock Count Report",
      value: "24",
      subtitle: "Counts Done",
      color: "purple",
      path: "/reports/stock-count",
    },

    {
      title: "Low Stock Report",
      value: "28",
      subtitle: "Items",
      color: "red",
      path: "/reports/low-stock",
    },

  ];

  const recentReports = [

    {
      name: "Inventory Report",
      generated: "20 Jun 2025 10:30 AM",
      range: "01 Jun 2025 - 20 Jun 2025",
      by: "Rahul Sharma",
    },

    {
      name: "Purchase Report",
      generated: "20 Jun 2025 09:15 AM",
      range: "01 Jan 2025 - 20 Jun 2025",
      by: "Amit Verma",
    },

    {
      name: "Supplier Report",
      generated: "19 Jun 2025 06:20 PM",
      range: "01 May 2025 - 31 May 2025",
      by: "Rahul Sharma",
    },

  ];

  return (

    <div className="space-y-8">

      {/* HEADER */}

      <div className="flex justify-between items-center">

        <div>

          <h1 className="text-4xl font-bold">
            Reports
          </h1>

        </div>

        <button className="bg-blue-600 text-white px-6 py-3 rounded-xl">
          Export All Reports
        </button>

      </div>

      {/* REPORT CARDS */}

      <div className="grid grid-cols-5 gap-5">

        {reportCards.map((card, index) => (

          <div
  key={index}
  onClick={() => navigate(card.path)}
  className={`rounded-2xl p-6 cursor-pointer transition-all duration-300 border ${
    location.pathname === card.path
      ? "bg-gradient-to-r from-blue-600 to-indigo-600 text-white shadow-xl border-blue-500 scale-105"
      : "bg-white hover:shadow-xl border-slate-200 hover:-translate-y-1"
  }`}
>

            <h3
  className={`font-semibold ${
    location.pathname === card.path
      ? "text-white"
      : "text-slate-600"
  }`}
>
              {card.title}
            </h3>

            <h1 className="text-4xl font-bold mt-4">
              {card.value}
            </h1>

            <p
  className={`mt-2 ${
    location.pathname === card.path
      ? "text-blue-100"
      : "text-slate-500"
  }`}
>
              {card.subtitle}
            </p>

          </div>

        ))}

      </div>

      {/* RECENT REPORTS */}
      {location.pathname === "/reports" && (

      <div className="bg-white rounded-2xl p-6 shadow-sm">

        <h2 className="text-2xl font-bold mb-6">
          Recent Reports
        </h2>

        <table className="w-full">

          <thead className="bg-slate-100">

            <tr>

              <th className="p-4 text-left">
                Report Name
              </th>

              <th className="p-4 text-left">
                Generated On
              </th>

              <th className="p-4 text-left">
                Date Range
              </th>

              <th className="p-4 text-left">
                Generated By
              </th>

              <th className="p-4 text-left">
                Action
              </th>

            </tr>

          </thead>

          <tbody>

            {recentReports.map((report, index) => (

              <tr
                key={index}
                className="border-b hover:bg-slate-50"
              >

                <td className="p-4 font-medium">
                  {report.name}
                </td>

                <td className="p-4">
                  {report.generated}
                </td>

                <td className="p-4">
                  {report.range}
                </td>

                <td className="p-4">
                  {report.by}
                </td>

                <td className="p-4">

                  <button className="text-blue-600 font-medium">
                    View
                  </button>

                </td>

              </tr>

            ))}

          </tbody>

        </table>

      </div>
      )}

      <div className="mt-8">
  <Outlet />
</div>

    </div>

  );

};

export default Reports;